### Query patients by last name
GET http://localhost:8091/patients?lastName=Smith
Accept: application/json

### Query patients by id
GET http://localhost:8091/patient/1
Accept: application/json

### Query patient visits by id
GET http://localhost:8091/patientsvisits/1
Accept: application/json

### Query patients with more than X visits
GET http://localhost:8091/patientswithmorethanxvisits?x=0
Accept: application/json


### Get patients by gender containing keyword
GET http://localhost:8091/patientsbygender?keyword=FE
Accept: application/json